context:
  version: "8.3.678"
package:
  name: magic
  version: ${{ version }}

source:
  url: https://github.com/RTimothyEdwards/magic/archive/refs/tags/${{ version }}.tar.gz
  sha256: 3f47b68d3ca2c0ef1cdf18916581a5ac3a529ecc83c6ad0d7cd8e1800d2c3614

build:
  number: 0
  skip: not target_platform.startswith("linux") 
  script:
    - export CFLAGS="$CFLAGS -D__NO_STRING_INLINES -DCPFunction='char**' -DCPPFunction='rl_completion_func_t' -std=gnu17 -fpermissive -Wno-incompatible-pointer-types -Wno-implicit-function-declaration -Wno-error=implicit-function-declaration -Wno-implicit-int -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -Wno-compare-distinct-pointer-types -Wno-error=compare-distinct-pointer-types"
    - export LIBRARY_PATH="$PREFIX/lib:$LIBRARY_PATH"
    - export C_INCLUDE_PATH="$PREFIX/include:$C_INCLUDE_PATH"
    - ./configure --prefix="${PREFIX}" --host="${HOST}" --with-tk="${PREFIX}/lib" 
    - make -j1 
    - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - make
    - ${{ stdlib('c') }}
    - pkg-config
  host:
    - libglu
    - freetype 
    - libgl-devel
    - xorg-libx11 
    - cairo
    - readline
    - tk
    - xorg-libice
    - xorg-libsm
    - xorg-libxext
    - xorg-libxmu
    - zlib
  run:
    - cairo
    - readline
    - tk
    - xorg-libice
    - xorg-libsm
    - xorg-libxext
    - xorg-libxmu
    - zlib

about:
  homepage: https://opencircuitdesign.com/magic/
  repository: https://github.com/RTimothyEdwards/magic
  summary: Magic VLSI layout tool
  description: 
    Magic is an open-source VLSI layout tool supporting circuit layout,
    design-rule checking, extraction, and multiple technology files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - proppy
    - curtisma
    - Xkhanh720
    - duyhieubui
